replicaCount: 1

environment: prod
clusterName: core-eks-prod

podLabels:
  app: payment-service
  cluster: core-eks-prod
  environment: prod

image:
  repository: 632638637624.dkr.ecr.us-east-1.amazonaws.com/payment-service
  tag: "v1"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  path: /payment-prod

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
